### ISSUE TITLE
Bug/Issue: Unable to delete organisation cos object is locked

### ISSUE THREAD

**Issue by samqi** [Sinar/sinar.organization#17]
**Describe the bug**
I accidentally created a duplicate organization, and am unable to delete organisation due to organization is locked

**To Reproduce (with screenshots)**
1. Go to Plone navigation -> Actions -> 'Delete'
2. Click on 'Delete' when seeing "Deleting overview" modal window
![image](https://github.com/user-attachments/assets/3eb1bb97-33e8-4b85-bd6c-2515a84db8d4)

3. See error "We’re sorry, but there seems to be an error…"
![image](https://github.com/user-attachments/assets/5870d963-258a-4447-9e22-7e4f14d86d69)

**Expected behavior**
Organisation is deleted after hitting "Delete"

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
  - Version 133.0

**Additional context**
Plone - I no longer see the **lock / unlock** option under any of the navigation 
(saw it before in Resources, but unsure if its always been unavailable in Organization)

**Comment by kaerumy** [comment]
This is usually temporary, similar to when two files open on Windows/Samba shared. It's unlocked automatically if not opened for editing after a short  period of time.
